"""empty message

Revision ID: 9877cfbc714b
Revises: f0da30e3d993
Create Date: 2024-05-06 19:42:15.451556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9877cfbc714b'
down_revision = 'f0da30e3d993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('lists',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text('\'{"list_ids": []}\'::jsonb'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('lists',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'{"list_ids": []}\'::jsonb'))

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.INTEGER(),
                                    autoincrement=False,
                                    nullable=False,
                                    server_default='0'))

    # ### end Alembic commands ###
